<?xml version="1.0" encoding="utf-8"?><Database Name="Users" Class="UsersDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Imie" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nazwisko" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Haslo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Skladnik" Member="Skladnik">
    <Type Name="Skladnik">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Opis" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Nazwa" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Skladnik_PS" Member="PS" ThisKey="Id" OtherKey="Id_skladnika" Type="PS" />
    </Type>
  </Table>
  <Table Name="dbo.PS" Member="PS">
    <Type Name="PS">
      <Column Name="Ilosc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_przepisu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Id_skladnika" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Skladnik_PS" Member="Skladnik" ThisKey="Id_skladnika" OtherKey="Id" Type="Skladnik" IsForeignKey="true" />
      <Association Name="Przepis_PS" Member="Przepis" ThisKey="Id_przepisu" OtherKey="Id" Type="Przepis" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Zdjecia" Member="Zdjecia">
    <Type Name="Zdjecia">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="zdjecie" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="id_przepisu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Przepis_Zdjecia" Member="Przepis" ThisKey="id_przepisu" OtherKey="Id" Type="Przepis" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Przepis" Member="Przepis">
    <Type Name="Przepis">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nazwa" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Opis" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Association Name="Przepis_PS" Member="PS" ThisKey="Id" OtherKey="Id_przepisu" Type="PS" />
      <Association Name="Przepis_Zdjecia" Member="Zdjecia" ThisKey="Id" OtherKey="id_przepisu" Type="Zdjecia" />
    </Type>
  </Table>
</Database>