<?xml version="1.0" encoding="utf-8"?><Database Name="Users" Class="UsersDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Imie" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nazwisko" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Haslo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Skladnik" Member="Skladnik">
    <Type Name="Skladnik">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Opis" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Nazwa" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="PS_Skladnik" Member="PS" ThisKey="Id" OtherKey="Id_skladnika" Type="PS" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Przepis" Member="Przepis">
    <Type Name="Przepis">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nazwa" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Opis" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="PS_Przepis" Member="PS" ThisKey="Id" OtherKey="Id_przepisu" Type="PS" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PS" Member="PS">
    <Type Name="PS">
      <Column Name="Ilosc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_przepisu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_skladnika" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PS_Skladnik" Member="Skladnik" ThisKey="Id_skladnika" OtherKey="Id" Type="Skladnik" />
      <Association Name="PS_Przepis" Member="Przepis" ThisKey="Id_przepisu" OtherKey="Id" Type="Przepis" />
    </Type>
  </Table>
</Database>